name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -sL https://supabase.com/cli/install/linux | bash
          sudo mv supabase /usr/local/bin/supabase
          supabase --version

      - name: Set up Supabase authentication
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase login --access-token "$SUPABASE_ACCESS_TOKEN"

      - name: Deploy Edge Function
        run: |
          supabase functions deploy ai-assistant


