name: Deploy Supabase Function

on:
  push:
    branches:
      - main  # 或你想部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Supabase CLI (v2.19.7)
        run: |
          curl -L "https://github.com/supabase/cli/releases/download/v2.19.7/supabase_2.19.7_linux_amd64.tar.gz" -o supabase.tar.gz
          tar -xzf supabase.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/
          supabase --version

      - name: Set Supabase secrets
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          supabase secrets set OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            PROJECT_URL="${{ secrets.PROJECT_URL }}" \
            PROJECT_ANON_KEY="${{ secrets.PROJECT_ANON_KEY }}"

      - name: Deploy Edge Function
        run: |
          supabase functions deploy ai-assistant
